import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  JoinColumn,
} from "typeorm";
import { Consulting } from "./consulting.entity";
import { StatusArea } from "../models/enums/kpi_status.enum";

/**
 * Represents a detected KPI area within a consulting session.
 *
 * Each area tracks its knowledge score, progression, and individual commercial proposal.
 * Areas are persisted in their own table and linked via ManyToOne to the Consulting entity.
 *
 * @entity
 * @table consulting_kpi_area
 */
@Entity({ name: "consulting_kpi_area" })
export class ConsultingKpiArea {
  @PrimaryGeneratedColumn()
  id!: number;

  /** Semantic identifier generated by the AI (e.g. "area_0_1234567890") */
  @Column({ type: "varchar" })
  areaId!: string;

  /** Name of the detected area in Spanish (e.g. "Infraestructura Tecnológica") */
  @Column({ type: "varchar" })
  name!: string;

  /** Latest knowledge score [0-10] assigned by the AI */
  @Column({ type: "float", default: 0 })
  actualScore!: number;

  /** Score from the previous analysis cycle */
  @Column({ type: "float", default: 0 })
  previousScore!: number;

  /** Total number of questions asked for this area */
  @Column({ type: "int", default: 0 })
  numQuestions!: number;

  /** Incremental AI-generated summary of the diagnosed problem in this area */
  @Column({ type: "text", nullable: true })
  summary!: string;

  /**
   * Commercial proposal generated in Phase 3.
   * Written in flowing executive Spanish paragraphs to sell a third-party solution.
   * Populated only when the final proposal phase is triggered.
   */
  @Column({ type: "text", nullable: true })
  proposal!: string;

  /** Current processing status of this area */
  @Column({ type: "enum", enum: StatusArea, default: StatusArea.PENDING })
  status!: StatusArea;

  // N:1 Relationship with Consulting
  @ManyToOne(() => Consulting, (consulting) => consulting.areas, {
    onDelete: "CASCADE",
  })
  @JoinColumn()
  consulting!: Consulting;
}
